---
name: lint

on:
  push:
    branches: master
  pull_request:
    branches: master
  schedule:
    - cron: "0 13 * * *"

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version: [28.1]
    steps:
      - uses: actions/checkout@v2
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - uses: cask/setup-cask@master
        if: steps.cache-cask-executable.outputs.cache-hit != 'true'
        with:
          version: snapshot
      - name: Lint elisp
        run: cask install && make lint
